version: "3"
services:
  api-server:
    image: airbnb-server:latest
    ports:
      - "8080:8080"
    container_name: api-vms
    environment:
      - SERVER_PORT=8080
      - POSTGRES_HOST=localhost
      - POSTGRES_PORT=5432
      - POSTGRES_DATABASE=airbnb-db
      - POSTGRES_USER=psadmin@airbnb-db
      - POSTGRES_PASSWORD=postgres
