com:
  airbnb:
    permitAll: /v3/api-docs/**,/swagger-ui/**,/actuator/**,/favicon.ico,/error,/api/v1/user/filter-available-users,/api/v1/card,/api/v1/card/**
#        oauth2:
#          provider: keycloak
#          keycloak:
#            realm: ${KEYCLOAK_REALM}
#            issuer-uri: ${KEYCLOAK_SCHEMA}://${KEYCLOAK_HOST}/realms/${edu.fpt.capstone.vms.oauth2.keycloak.realm}
#            jwk-set-uri: ${edu.fpt.capstone.vms.oauth2.keycloak.issuer-uri}/protocol/openid-connect/certs
#            client-id: vms-api
#            principal-attribute: preferred_username
#            credentials-secret: ${KEYCLOAK_CREDENTIALS}
#            admin-username: ${KEYCLOAK_REALM_ADMIN_USER}
#            admin-password: ${KEYCLOAK_REALM_ADMIN_PASS}
#            ignore-default-roles: default-roles-${edu.fpt.capstone.vms.oauth2.keycloak.realm},offline_access,uma_authorization

management:
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always
  endpoints:
    web:
      cors:
        allowed-origins: http://localhost:3000
      exposure:
        include: health,info,metrics,prometheus,bindings,beans,env,loggers,streamsbindings
  metrics:
    tags:
      application: ${spring.application.name}

server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: airbnb-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DATABASE}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: none
    generate-ddl: true
    properties:
      javax:
        persistence:
          create-database-schemas: true


#  liquibase:
#    change-log: classpath:db/changelog-master.yml
  main:
    allow-bean-definition-overriding: true
#  data:
#    redis:
#      host: ${REDIS_HOST}
#      port: ${REDIS_PORT}
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: ${edu.fpt.capstone.vms.oauth2.keycloak.issuer-uri}
#          jwk-set-uri: ${edu.fpt.capstone.vms.oauth2.keycloak.jwk-set-uri}
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
springdoc:
  cache:
    disabled: true
  swagger-ui:
    use-root-path: true
  api-docs:
    enabled: true

logging:
  level:
    org.springframework.security: TRACE
    org.springframework.security.web.FilterChainProxy: TRACE
    root: info
    web: info
  file:
    name: ./logs/info.log

#schedule:
#  cleaningImage:
#    time: 0 0 22 * * *
