spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/airbnb_dev
    username: dev_user
    password: dev_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

flyway:
  enabled: true
  locations: classpath:db/migration