version: '3.8'
services:
  postgres:
    container_name: postgresql
    image: postgres:latest
    environment:
      POSTGRES_USER: psadmin@airbnb-db
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./volume/postgresql/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
      - "5431:5432"
    networks:
      - airbnb

networks:
  airbnb:
    name: airbnb-network
    driver: bridge
